In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.decomposition import TruncatedSVD
import random
# import seaborn as sns
import os.path as path
import os
import matplotlib
import matplotlib.font_manager
import matplotlib.pyplot as plt # graphs plotting
# from Bio import SeqIO # some BioPython that will come in handy
#matplotlib inline
import numpy
import csv

from matplotlib import rc

from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso, LogisticRegression
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn import svm

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

import pandas as pd
import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix

from sklearn.neighbors import KNeighborsClassifier

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

from pandas import DataFrame

from sklearn.model_selection import KFold
from sklearn.model_selection import RepeatedKFold

from sklearn.metrics import confusion_matrix

from numpy import mean
#from Bio.SeqUtils.ProtParam import ProteinAnalysis


from itertools import cycle

from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp
from sklearn.metrics import roc_auc_score

import statistics
import pandas as pd
import csv
import numpy as np
import itertools
from itertools import product

import timeit

import math

# for Arial typefont
matplotlib.rcParams['font.family'] = 'Arial'


## for Palatino and other serif fonts use:
# rc('font',**{'family':'serif','serif':['Palatino']})
# matplotlib.rcParams['mathtext.fontset'] = 'cm'

## for LaTeX typefont
# matplotlib.rcParams['mathtext.fontset'] = 'stix'
# matplotlib.rcParams['font.family'] = 'STIXGeneral'

## for another LaTeX typefont
# rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})

# rc('text', usetex = True)

print("Packages imported")

Packages imported


# Reading Antigene Nanobody Dataset

In [ ]:

# Read the Excel file
excel_file_path = 'sample_data/Ag_NbBindingDatawithSequences_Sheet1.csv'


data = []
counter = 0
# Open the CSV file in text mode
with open(excel_file_path, 'r') as file:
    # Create a CSV reader
    csv_reader = csv.reader(file)

    # Loop over each row in the CSV file
    for row in csv_reader:
        if counter>0:
            aa = str(row).split(",")
            aa[0] = aa[0].replace("[","").replace("\'","").replace(" ","").replace("]","")
            aa[1] = aa[1].replace("[","").replace("\'","").replace(" ","").replace("]","")
            aa[2] = aa[2].replace("[","").replace("\'","").replace(" ","").replace("]","")
            aa[3] = aa[3].replace("[","").replace("\'","").replace(" ","").replace("]","")
            aa[4] = aa[4].replace("[","").replace("\'","").replace(" ","").replace("]","")
            aa[5] = aa[5].replace("[","").replace("\'","").replace(" ","").replace("]","")
            aa[6] = aa[6].replace("[","").replace("\'","").replace(" ","").replace("]","")
            aa[7] = aa[7].replace("[","").replace("\'","").replace(" ","").replace("]","")
            aa[8] = aa[8].replace("[","").replace("\'","").replace(" ","").replace("]","")
            data.append(aa)
        counter = counter + 1
#         print(row)


In [ ]:
(data[0]),len(data)

(['sdAb_6274_Sy',
  'NB_1_AG_1',
  'NTV4',
  'SyntheticConstruct',
  'AG_1',
  'Vascularendothelialgrowthfactor(VEGF)receptorVEGFR-2domain3(VEGFRD3)',
  'MAQVQLLESGGGLVQPGGSLRLSCAASGVTITDEDMTRVRQAPGKGLEWVSSILNTGGSTYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAAVHEKAADMNFWGQGTLVTVSS',
  'DHNPFISVEWLKGPILEATAGDELVKLPVKLAAYPPPEFQWYKDGKALSGRHSPHALVLKEVTEASTGTYTLALWNSAAGLRRNISLELVVNVPPQIHEKEASSPSIYSRHSRQALTCTAYGVPLPLSIQWHWRPWTPCKMFAQRSLRRRQQQDLMPQCRDWRAVTTQDAVNPIESLDTWTEFVEGKNKTVSKLVIQNANVSAMYKCVVSNKVGQDERLIYFYVTTHHHHHH',
  '4BSJ_1'],
 365)

In [ ]:
(data[0][6])

'MAQVQLLESGGGLVQPGGSLRLSCAASGVTITDEDMTRVRQAPGKGLEWVSSILNTGGSTYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAAVHEKAADMNFWGQGTLVTVSS'

In [ ]:
len(data[0][6])

121

In [ ]:
(data[0][7])

'DHNPFISVEWLKGPILEATAGDELVKLPVKLAAYPPPEFQWYKDGKALSGRHSPHALVLKEVTEASTGTYTLALWNSAAGLRRNISLELVVNVPPQIHEKEASSPSIYSRHSRQALTCTAYGVPLPLSIQWHWRPWTPCKMFAQRSLRRRQQQDLMPQCRDWRAVTTQDAVNPIESLDTWTEFVEGKNKTVSKLVIQNANVSAMYKCVVSNKVGQDERLIYFYVTTHHHHHH'

In [ ]:
len(data[0][7])

232

# Reading Alignment Distance Matrix

In [ ]:

# Read the Excel file
excel_file_path = 'sample_data/Antibodies_Pairwise_Distance_Matrix.csv'


distance_matrix = []
header_name = []

counter = 0
# Open the CSV file in text mode
with open(excel_file_path, 'r') as file:
    # Create a CSV reader
    csv_reader = csv.reader(file)

    # Loop over each row in the CSV file
    for row in csv_reader:
        if counter>0:
            aa = str(row).split(",")
            aa_arr = []
            for j in range(1,len(aa)):
                aa_arr.append(float(aa[j].replace(" ","").replace("\'","").replace("]","")))
            distance_matrix.append(aa_arr)
            header_name.append(aa[0].replace("[","").replace("]","").replace("\'","").replace(" ",""))
        counter = counter + 1
#         print(row)


In [ ]:
header_name[0:10],len(header_name)

(['AG_1',
  'AG_2',
  'AG_3',
  'AG_39',
  'AG_4',
  'AG_5',
  'AG_6',
  'AG_7',
  'AG_8',
  'AG_10'],
 47)

In [ ]:
nanobody_sequences = []
len_nanobody_sequences = []
antigene_sequences = []
len_antigene_sequences = []
binding_label = []
nanobody_name = []
antigen_name = []
antigene_id_org = []

for i in range(len(data)):
    temp = data[i]
    nanobody_sequences.append(temp[6])
    len_nanobody_sequences.append(len(temp[6]))
    antigene_sequences.append(temp[7])
    len_antigene_sequences.append(len(temp[7]))
    binding_label.append("Yes")
    nanobody_name.append(temp[2])
    antigen_name.append(temp[5])
    antigene_id_org.append(temp[4])

In [ ]:
len(nanobody_sequences),antigene_id_org[0],len_nanobody_sequences[0],len_antigene_sequences[0]

(365, 'AG_1', 121, 232)

# Max and Min Length of Antigens

In [ ]:
max(len_antigene_sequences),min(len_antigene_sequences)

(1816, 158)

# Max and Min Length of Antibodies

In [ ]:
max(len_nanobody_sequences),min(len_nanobody_sequences)

(175, 104)

# Getting all possible NOT binding information

In [ ]:
nanobody_sequences_NO = []
antigene_sequences_NO = []
binding_label_NO = []
nanobody_name_NO = []
antigen_name_NO = []
antigene_id_NO = []
antigene_id_YES = []


for i in range(len(nanobody_sequences)):
    name_NB = nanobody_name[i]
    name_AG = antigen_name[i]
    nb_seq = nanobody_sequences[i]
    antigene_id_test = antigene_id_org[i]
    for j in range(len(nanobody_sequences)):
        name_AG_new = antigen_name[j]
        if name_AG==name_AG_new:
            a=1
        else:
            nanobody_sequences_NO.append(nb_seq)
            antigene_sequences_NO.append(antigene_sequences[j])
            binding_label_NO.append("No")
            nanobody_name_NO.append(nanobody_name[j])
            antigen_name_NO.append(antigen_name[j])
            antigene_id_NO.append(antigene_id_org[j])
            antigene_id_YES.append(antigene_id_test)

In [ ]:
# antigene_id_YES[0:10],antigene_id_NO[0:10],len(antigene_id_NO)

distance_values = []

for i in range(len(nanobody_sequences_NO)):
# for i in range(0,10):
    row_id = antigene_id_YES[i]
    row_val = (np.where(np.array(header_name) == row_id))[0][0]

    col_id = antigene_id_NO[i]
    col_val = (np.where(np.array(header_name) == col_id))[0][0]

#     print(row_val,",",col_val)

    distance_values.append(np.array(distance_matrix)[row_val,col_val])

In [ ]:
id_val = 10000
antigene_id_YES[id_val],antigene_id_NO[id_val],distance_values[id_val],len(distance_values),len(nanobody_sequences_NO)

('AG_8', 'AG_47', 0.89, 126490, 126490)

# Filter based on distance values

In [ ]:
filtered_No_nanobody_sequences = []
filtered_No_antigene_sequences = []
filtered_No_distance_values = []
filtered_No_label_value = []

No_distance_value_threshold = 0.85

for i in range(len(distance_values)):
    if distance_values[i] >= No_distance_value_threshold:
        filtered_No_nanobody_sequences.append(nanobody_sequences_NO[i])
        filtered_No_antigene_sequences.append(antigene_sequences_NO[i])
        filtered_No_distance_values.append(distance_values[i])
        filtered_No_label_value.append("No")

len(filtered_No_nanobody_sequences),len(nanobody_sequences_NO)

(108050, 126490)

In [ ]:
filtered_Yes_nanobody_sequences = []
filtered_Yes_antigene_sequences = []
filtered_Yes_distance_values = []
filtered_Yes_label_value = []

Yes_distance_value_threshold = 0.20

for i in range(len(distance_values)):
    if distance_values[i] <= Yes_distance_value_threshold:
        filtered_Yes_nanobody_sequences.append(nanobody_sequences_NO[i])
        filtered_Yes_antigene_sequences.append(antigene_sequences_NO[i])
        filtered_Yes_distance_values.append(distance_values[i])
        filtered_Yes_label_value.append("Yes")

len(filtered_Yes_nanobody_sequences),len(nanobody_sequences_NO)

(1388, 126490)

# Getting Random Subset

In [ ]:
# Set the random seed for reproducibility
np.random.seed(123)

# Calculate the number of rows to select (20% of the total rows)
rows_percentage_selected = 1.6
num_rows = int((rows_percentage_selected/100) * len(filtered_No_nanobody_sequences))
# Select random rows
nanobody_sequences_NO_random_rows = np.random.choice(filtered_No_nanobody_sequences, size=num_rows, replace=False)
antigene_sequences_NO_random_rows = np.random.choice(filtered_No_antigene_sequences, size=num_rows, replace=False)
binding_label_NO_random_rows = np.random.choice(filtered_No_label_value, size=num_rows, replace=False)

len(nanobody_sequences_NO_random_rows),len(filtered_No_nanobody_sequences)

(1728, 108050)

In [ ]:
nanobody_sequences_NO_random_rows[0]

'DVQLVESGGGLVQPGGSLRLSCAASGFTFSSYYMSWARQAPGKGPEWVSTINTGGGRMGYADSVKGRFTISRDNTKNTLYLHMNSLKPEDTALYYCARGDYDDSLRRRYWGQGTQVTVSS'

# Merging Data

In [ ]:
nanobody_sequences_full = nanobody_sequences[:]
antigene_sequences_full = antigene_sequences[:]
labels_full = binding_label[:]

for i in range(len(nanobody_sequences_NO_random_rows)):
    nanobody_sequences_full.append(nanobody_sequences_NO_random_rows[i])
    antigene_sequences_full.append(antigene_sequences_NO_random_rows[i])
    labels_full.append(binding_label_NO_random_rows[i])


# filtered_Yes_nanobody_sequences.append(nanobody_sequences_NO[i])
# filtered_Yes_antigene_sequences.append(antigene_sequences_NO[i])
# filtered_Yes_distance_values.append(distance_values[i])
# filtered_Yes_label_value.append("Yes")

for i in range(len(filtered_Yes_nanobody_sequences)):
    nanobody_sequences_full.append(filtered_Yes_nanobody_sequences[i])
    antigene_sequences_full.append(filtered_Yes_antigene_sequences[i])
    labels_full.append(filtered_Yes_label_value[i])


len(nanobody_sequences),len(nanobody_sequences_NO_random_rows),len(filtered_Yes_nanobody_sequences),len(nanobody_sequences_full)

(365, 1728, 1388, 3481)

In [ ]:
idx = pd.Index(labels_full) # creates an index which allows counting the entries easily
print('Here are all of the viral species in the dataset: \n', len(idx),"entries in total")
aq = idx.value_counts()
print(aq)

Here are all of the viral species in the dataset: 
 3481 entries in total
Yes    1753
No     1728
dtype: int64


# lables as Int

In [ ]:
unique_hst = list(np.unique(labels_full))

int_hosts = []
for ind_unique in range(len(labels_full)):
    variant_tmp = labels_full[ind_unique]
    ind_tmp = unique_hst.index(variant_tmp)
    int_hosts.append(ind_tmp)

print(len(int_hosts))
print(int_hosts[0])
print(int_hosts[3480])
print("Attribute data preprocessing Done")

3481
1
1
Attribute data preprocessing Done


# Create tokenizer for 3Kmer AAs (NB_WORDS = 8002), 1- 8000 for 3kmer AAs , 0 for padding , and 8001 for unk


In [ ]:
from keras.preprocessing.text import Tokenizer
import itertools
def get_tokenizer():
    AA = ['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y']
    c = itertools.product(AA,AA,AA)
    res=[]
    for i in c:
        temp=i[0]+i[1]+i[2]
        res.append(temp)
    res=np.array(res)
    #print(len(res))
    NB_WORDS = 8002
    tokenizer = Tokenizer(num_words=NB_WORDS)
    tokenizer.fit_on_texts(res)
    unk_AA_index = tokenizer.word_index
    unk_AA_index['<pad>'] = 0
    unk_AA_index = tokenizer.word_index
    unk_AA_index['<unk>'] = 8001

    return tokenizer

In [ ]:
tokenizer = get_tokenizer()
count = 0
for index, char in enumerate(tokenizer.word_index):
  print(index, char)
  count += 1
  if count == 5:
    break
print(index)
print(tokenizer.word_index)


0 aaa
1 aac
2 aad
3 aae
4 aaf
4
{'aaa': 1, 'aac': 2, 'aad': 3, 'aae': 4, 'aaf': 5, 'aag': 6, 'aah': 7, 'aai': 8, 'aak': 9, 'aal': 10, 'aam': 11, 'aan': 12, 'aap': 13, 'aaq': 14, 'aar': 15, 'aas': 16, 'aat': 17, 'aav': 18, 'aaw': 19, 'aay': 20, 'aca': 21, 'acc': 22, 'acd': 23, 'ace': 24, 'acf': 25, 'acg': 26, 'ach': 27, 'aci': 28, 'ack': 29, 'acl': 30, 'acm': 31, 'acn': 32, 'acp': 33, 'acq': 34, 'acr': 35, 'acs': 36, 'act': 37, 'acv': 38, 'acw': 39, 'acy': 40, 'ada': 41, 'adc': 42, 'add': 43, 'ade': 44, 'adf': 45, 'adg': 46, 'adh': 47, 'adi': 48, 'adk': 49, 'adl': 50, 'adm': 51, 'adn': 52, 'adp': 53, 'adq': 54, 'adr': 55, 'ads': 56, 'adt': 57, 'adv': 58, 'adw': 59, 'ady': 60, 'aea': 61, 'aec': 62, 'aed': 63, 'aee': 64, 'aef': 65, 'aeg': 66, 'aeh': 67, 'aei': 68, 'aek': 69, 'ael': 70, 'aem': 71, 'aen': 72, 'aep': 73, 'aeq': 74, 'aer': 75, 'aes': 76, 'aet': 77, 'aev': 78, 'aew': 79, 'aey': 80, 'afa': 81, 'afc': 82, 'afd': 83, 'afe': 84, 'aff': 85, 'afg': 86, 'afh': 87, 'afi': 88, 'afk': 8

# Method to spilt sequences to 3kmer tokens



In [ ]:
def sentence2word(str_set):
    word_seq=[]
    for sr in str_set:
        tmp=[]
        for i in range(len(sr)-2):
            if('B' in sr[i:i+3]):
                tmp.append('<unk>')
            elif('J' in sr[i:i+3]):
                tmp.append('<unk>')
            elif('O' in sr[i:i+3]):
                tmp.append('<unk>')
            elif('U'  in sr[i:i+3]):
                tmp.append('<unk>')
            elif('X' in sr[i:i+3]):
                tmp.append('<unk>')
            elif('Z' in sr[i:i+3]):
                tmp.append('<unk>')
            else:
                tmp.append(sr[i:i+3])
        word_seq.append(' '.join(tmp))
    return word_seq

# Method to convert 3kmer tokens to integer numbers according to the 3kmer tokenizer and apply pad_sequences

In [ ]:
from keras.utils import pad_sequences
def word2num(wordseq,tokenizer,MAX_LEN):
    sequences = tokenizer.texts_to_sequences(wordseq)
    numseq = pad_sequences(sequences, maxlen=MAX_LEN)
    return numseq, sequences

# Method to convert sequences to integer numbers

In [ ]:
def sentence2num(str_set,tokenizer,MAX_LEN):
    wordseq=sentence2word(str_set)
    numseq, sequences =word2num(wordseq,tokenizer,MAX_LEN)
    return numseq, wordseq, sequences

# Get the 3kmer data of the Nanobodies and Antigens

In [ ]:
def get_data(nanobodies,antigens):
    tokenizer=get_tokenizer()
    MAX_LEN=175
    X_Nb, Nb_words, Nb_nums=sentence2num(nanobodies,tokenizer,MAX_LEN)
    MAX_LEN=1816
    X_Ag, Ag_words, Ag_nums=sentence2num(antigens,tokenizer,MAX_LEN)

    return X_Nb,X_Ag, Nb_words, Nb_nums, Ag_words, Ag_nums

# Call of the above method and pass to it the sequences of the Nanobodies and Antigens

In [ ]:
X_Nb,X_Ag, Nb_words, Nb_nums, Ag_words, Ag_nums=get_data(nanobody_sequences_full,antigene_sequences_full)

In [ ]:
Nb_words[0]

'MAQ AQV QVQ VQL QLL LLE LES ESG SGG GGG GGL GLV LVQ VQP QPG PGG GGS GSL SLR LRL RLS LSC SCA CAA AAS ASG SGV GVT VTI TIT ITD TDE DED EDM DMT MTR TRV RVR VRQ RQA QAP APG PGK GKG KGL GLE LEW EWV WVS VSS SSI SIL ILN LNT NTG TGG GGS GST STY TYY YYA YAD ADS DSV SVK VKG KGR GRF RFT FTI TIS ISR SRD RDN DNS NSK SKN KNT NTL TLY LYL YLQ LQM QMN MNS NSL SLR LRA RAE AED EDT DTA TAV AVY VYY YYC YCA CAA AAV AVH VHE HEK EKA KAA AAD ADM DMN MNF NFW FWG WGQ GQG QGT GTL TLV LVT VTV TVS VSS'

In [ ]:
type(Nb_words)

list

In [ ]:
type(Nb_nums)

list

In [ ]:
Nb_nums[0]

In [ ]:
print(X_Nb[0])

[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
 4014  278 5554 7070 5390 3784 3676 1506 6106 2106 2110 2198 3954 7073
 5446 4906 2116 2310 6195 3890 5796 3902 6021  401   16  306 6118 2357
 7128 6557 3123 6444  863 1251 1017 4335 6698 5955 7094 5861 5213  246
 4909 2166 3310 2184 3679 1578 7556 7116 6308 6150 2992 3837 4726 6506
 2116 2317 6340 6800 7981 7603   56 1118 6349 6966 3315 2285 5697 1928
 6556 3115 6283 5652 1036 4709 6172 3437 4730 6600 3990 7794 3871 5412
 4236 4710 6195 3881 5604   63 1257 1121 6418  360 7200 7982 7621  401
   18  347 6924 2469 1361 3201    3   51 1012 4225 4499 1966 7314 2266
 5317 2330 6598 3957 7138 6756 7116]


In [ ]:
print(len(X_Nb[0]))

175


In [ ]:
print(X_Nb[1])

[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0 4014  278 5554 7070 5390
 3784 3676 1506 6106 2106 2110 2198 3954 7073 5446 4906 2116 2310 6195
 3890 5796 3902 6021  401   16  306 6120 2396 7918 6348 6952 3023 4445
  891 1817 4339 6778 7555 7094 5861 5213  246 4909 2166 3310 2184 3679
 1578 7556 7116 6308 6156 3118 6341 6803   46  916 2317 6340 6800 7981
 7603   56 1118 6349 6966 3315 2285 5697 1928 6556 3115 6283 5652 1036
 4709 6172 3437 4730 6600 3990 7794 3871 5412 4236 4710 6195 3881 5604
   63 1257 1121 6418  360 7200 7982 7621  401   15  298 5946 6906 2115
 2283 5650  986 3719 2373 7460 5184 7670 1383 3660 1199 7966 7314 2266
 5317 2330 6598 3957 7138 6756 7116]


In [ ]:
print(len(X_Nb[1]))

175


In [ ]:
print(X_Ag[0])

[   0    0    0 ... 2527 2527 2527]


In [ ]:
print(len(X_Ag[0]))

1816


In [ ]:
print(X_Ag[1])

[   0    0    0 ... 2527 2527 2527]


In [ ]:
print(len(X_Ag[1]))

1816


In [ ]:
len(labels_full)

3481

In [ ]:
type(labels_full)

list

# Save the sequences of nanobodies and antigens after pre-processing based on 3kmer

In [ ]:
Data_dir ="sample_data/"
np.savez(Data_dir+'Nb_Ag_pairs_3Kmer.npz',X_Nb=X_Nb,X_Ag=X_Ag,y=np.array(int_hosts))

In [ ]:
Nb_Ag_pairs = np.load("sample_data/Nb_Ag_pairs_3Kmer.npz")

In [ ]:
X_Nb, X_Ag, y = Nb_Ag_pairs['X_Nb'], Nb_Ag_pairs['X_Ag'], Nb_Ag_pairs['y']

In [ ]:
len(X_Nb) , len(X_Nb[0])

(3481, 175)

In [ ]:
X_Nb

array([[   0,    0,    0, ..., 7138, 6756, 7116],
       [   0,    0,    0, ..., 7138, 6756, 7116],
       [   0,    0,    0, ..., 7138, 6756, 7116],
       ...,
       [   0,    0,    0, ..., 7138, 6756, 7116],
       [   0,    0,    0, ..., 7138, 6756, 7116],
       [   0,    0,    0, ..., 7138, 6756, 7116]], dtype=int32)

In [ ]:
type(X_Nb)

numpy.ndarray

In [ ]:
X_Ag

array([[   0,    0,    0, ..., 2527, 2527, 2527],
       [   0,    0,    0, ..., 2527, 2527, 2527],
       [   0,    0,    0, ..., 2527, 2527, 2527],
       ...,
       [   0,    0,    0, ..., 7058, 5156, 7104],
       [   0,    0,    0, ..., 7058, 5156, 7104],
       [   0,    0,    0, ..., 7058, 5156, 7104]], dtype=int32)

In [ ]:
len(X_Ag) , len(X_Ag[0])

(3481, 1816)

In [ ]:
type(X_Ag)

numpy.ndarray

In [ ]:
type(y)

numpy.ndarray

In [ ]:
len(y)

3481

In [ ]:
pip install Keras-Preprocessing

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 741.3 kB/s eta 0:00:00


# load the AA tokenizer 1 kmer (NB_WORDS = 21)



In [ ]:
import pickle
with open("sample_data/AminoAcidTokenizer.pickle","rb") as input_:
    tokenizer=pickle.load(input_)

In [ ]:
type(tokenizer)

keras_preprocessing.text.Tokenizer

# read the blosum embedding from the csv file as pandas datafram

In [ ]:
raw_blosum=pd.read_csv('sample_data/BLOSUM.csv')


In [ ]:
raw_blosum

AA    Dim1    Dim2    Dim3    Dim4    Dim5    Dim6    Dim7    Dim8    Dim9  \
0   A  0.2901  0.0446  0.0427  0.0410  0.0650  0.0559  0.0552  0.0783  0.0420   
1   R  0.0310  0.3450  0.0449  0.0299  0.0163  0.0735  0.0497  0.0229  0.0458   
2   N  0.0256  0.0388  0.3169  0.0690  0.0163  0.0441  0.0405  0.0391  0.0534   
3   D  0.0297  0.0310  0.0831  0.3974  0.0163  0.0471  0.0902  0.0337  0.0382   
4   C  0.0216  0.0078  0.0090  0.0075  0.4837  0.0088  0.0074  0.0108  0.0076   
5   Q  0.0256  0.0484  0.0337  0.0299  0.0122  0.2147  0.0645  0.0189  0.0382   
6   E  0.0405  0.0523  0.0494  0.0914  0.0163  0.1029  0.2965  0.0256  0.0534   
7   G  0.0783  0.0329  0.0652  0.0466  0.0325  0.0412  0.0350  0.5101  0.0382   
8   H  0.0148  0.0233  0.0315  0.0187  0.0081  0.0294  0.0258  0.0135  0.3550   
9   I  0.0432  0.0233  0.0225  0.0224  0.0447  0.0265  0.0221  0.0189  0.0229   
10  L  0.0594  0.0465  0.0315  0.0280  0.0650  0.0471  0.0368  0.0283  0.0382   
11  K  0.0445  0.1202  0.0539  0.0448  0.0203  0.0912  0.0755  0.0337  0.0458   
12  M  0.0175  0.0155  0.0112  0.0093  0.0163  0.0206  0.0129  0.0094  0.0153   
13  F  0.0216  0.0174  0.0180  0.0149  0.0203  0.0147  0.0166  0.0162  0.0305   
14  P  0.0297  0.0194  0.0202  0.0224  0.0163  0.0235  0.0258  0.0189  0.0191   
15  S  0.0850  0.0446  0.0697  0.0522  0.0407  0.0559  0.0552  0.0513  0.0420   
16  T  0.0499  0.0349  0.0494  0.0354  0.0366  0.0412  0.0368  0.0297  0.0267   
17  W  0.0054  0.0058  0.0045  0.0037  0.0041  0.0059  0.0055  0.0054  0.0076   
18  Y  0.0175  0.0174  0.0157  0.0112  0.0122  0.0206  0.0166  0.0108  0.0573   
19  V  0.0688  0.0310  0.0270  0.0243  0.0569  0.0353  0.0313  0.0243  0.0229   

    ...   Dim11   Dim12   Dim13   Dim14   Dim15   Dim16   Dim17   Dim18  \
0   ...  0.0445  0.0570  0.0522  0.0338  0.0568  0.1099  0.0730  0.0303   
1   ...  0.0243  0.1071  0.0321  0.0190  0.0258  0.0401  0.0355  0.0227   
2   ...  0.0142  0.0415  0.0201  0.0169  0.0233  0.0541  0.0434  0.0152   
3   ...  0.0152  0.0415  0.0201  0.0169  0.0310  0.0489  0.0375  0.0152   
4   ...  0.0162  0.0086  0.0161  0.0106  0.0103  0.0175  0.0178  0.0076   
5   ...  0.0162  0.0535  0.0281  0.0106  0.0207  0.0332  0.0276  0.0152   
6   ...  0.0202  0.0708  0.0281  0.0190  0.0362  0.0524  0.0394  0.0227   
7   ...  0.0213  0.0432  0.0281  0.0254  0.0362  0.0663  0.0434  0.0303   
8   ...  0.0101  0.0207  0.0161  0.0169  0.0129  0.0192  0.0138  0.0152   
9   ...  0.1154  0.0276  0.1004  0.0634  0.0258  0.0297  0.0533  0.0303   
10  ...  0.3755  0.0432  0.1968  0.1142  0.0362  0.0419  0.0651  0.0530   
11  ...  0.0253  0.2781  0.0361  0.0190  0.0413  0.0541  0.0454  0.0227   
12  ...  0.0496  0.0155  0.1606  0.0254  0.0103  0.0157  0.0197  0.0152   
13  ...  0.0547  0.0155  0.0482  0.3869  0.0129  0.0209  0.0237  0.0606   
14  ...  0.0142  0.0276  0.0161  0.0106  0.4935  0.0297  0.0276  0.0076   
15  ...  0.0243  0.0535  0.0361  0.0254  0.0439  0.2199  0.0927  0.0227   
16  ...  0.0334  0.0397  0.0402  0.0254  0.0362  0.0820  0.2465  0.0227   
17  ...  0.0071  0.0052  0.0080  0.0169  0.0026  0.0052  0.0059  0.4924   
18  ...  0.0223  0.0173  0.0241  0.0888  0.0129  0.0175  0.0178  0.0682   
19  ...  0.0962  0.0328  0.0924  0.0550  0.0310  0.0419  0.0710  0.0303   

     Dim19   Dim20  
0   0.0405  0.0700  
1   0.0280  0.0219  
2   0.0218  0.0165  
3   0.0187  0.0178  
4   0.0093  0.0192  
5   0.0218  0.0165  
6   0.0280  0.0233  
7   0.0249  0.0247  
8   0.0467  0.0082  
9   0.0436  0.1646  
10  0.0685  0.1303  
11  0.0312  0.0261  
12  0.0187  0.0316  
13  0.1308  0.0357  
14  0.0156  0.0165  
15  0.0312  0.0329  
16  0.0280  0.0494  
17  0.0280  0.0055  
18  0.3178  0.0206  
19  0.0467  0.2689  

[20 rows x 21 columns]

In [ ]:
raw_blosum.AA

0     A
1     R
2     N
3     D
4     C
5     Q
6     E
7     G
8     H
9     I
10    L
11    K
12    M
13    F
14    P
15    S
16    T
17    W
18    Y
19    V
Name: AA, dtype: object

# Create numpy array for the blosum embeddings

In [ ]:
blosum=np.zeros((21,20),dtype=np.float32)

In [ ]:
blosum

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

# Store the blosum embeddings into the numpy array

In [ ]:
count=0
for index, char in enumerate(tokenizer.word_index):
    print(index , char)
    count+=1;
    blosum[index+1,:]= np.array(raw_blosum.loc[raw_blosum.AA==char.upper()])[:,1:21].reshape(20,)
    print(blosum[index+1,:])
    if count ==20:
        break

0 l
[0.0594 0.0465 0.0315 0.028  0.065  0.0471 0.0368 0.0283 0.0382 0.1679
 0.3755 0.0432 0.1968 0.1142 0.0362 0.0419 0.0651 0.053  0.0685 0.1303]
1 s
[0.085  0.0446 0.0697 0.0522 0.0407 0.0559 0.0552 0.0513 0.042  0.025
 0.0243 0.0535 0.0361 0.0254 0.0439 0.2199 0.0927 0.0227 0.0312 0.0329]
2 e
[0.0405 0.0523 0.0494 0.0914 0.0163 0.1029 0.2965 0.0256 0.0534 0.0177
 0.0202 0.0708 0.0281 0.019  0.0362 0.0524 0.0394 0.0227 0.028  0.0233]
3 a
[0.2901 0.0446 0.0427 0.041  0.065  0.0559 0.0552 0.0783 0.042  0.0471
 0.0445 0.057  0.0522 0.0338 0.0568 0.1099 0.073  0.0303 0.0405 0.07  ]
4 k
[0.0445 0.1202 0.0539 0.0448 0.0203 0.0912 0.0755 0.0337 0.0458 0.0236
 0.0253 0.2781 0.0361 0.019  0.0413 0.0541 0.0454 0.0227 0.0312 0.0261]
5 g
[0.0783 0.0329 0.0652 0.0466 0.0325 0.0412 0.035  0.5101 0.0382 0.0206
 0.0213 0.0432 0.0281 0.0254 0.0362 0.0663 0.0434 0.0303 0.0249 0.0247]
6 v
[0.0688 0.031  0.027  0.0243 0.0569 0.0353 0.0313 0.0243 0.0229 0.1767
 0.0962 0.0328 0.0924 0.055  0.031  0.0419 0

In [ ]:
blosum

array([[0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
        0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
        0.    , 0.    , 0.    , 0.    ],
       [0.0594, 0.0465, 0.0315, 0.028 , 0.065 , 0.0471, 0.0368, 0.0283,
        0.0382, 0.1679, 0.3755, 0.0432, 0.1968, 0.1142, 0.0362, 0.0419,
        0.0651, 0.053 , 0.0685, 0.1303],
       [0.085 , 0.0446, 0.0697, 0.0522, 0.0407, 0.0559, 0.0552, 0.0513,
        0.042 , 0.025 , 0.0243, 0.0535, 0.0361, 0.0254, 0.0439, 0.2199,
        0.0927, 0.0227, 0.0312, 0.0329],
       [0.0405, 0.0523, 0.0494, 0.0914, 0.0163, 0.1029, 0.2965, 0.0256,
        0.0534, 0.0177, 0.0202, 0.0708, 0.0281, 0.019 , 0.0362, 0.0524,
        0.0394, 0.0227, 0.028 , 0.0233],
       [0.2901, 0.0446, 0.0427, 0.041 , 0.065 , 0.0559, 0.0552, 0.0783,
        0.042 , 0.0471, 0.0445, 0.057 , 0.0522, 0.0338, 0.0568, 0.1099,
        0.073 , 0.0303, 0.0405, 0.07  ],
       [0.0445, 0.1202, 0.0539, 0.0448, 0.0203, 0.0912, 0.0755, 0.0337,
   

In [ ]:
len(blosum), len(blosum[0])

(21, 20)

# Save the blosum embeddings as npy file

In [ ]:
path = ('sample_data/blosum_embedding.npy')
np.save(path, blosum)

# Method to spilt sequences to 1kmer tokens

In [ ]:
def sentence2AA(str_set):
    AA_seq=[]
    for sr in str_set:
        tmp=[]
        for i in range(len(sr)):
          tmp.append(sr[i])
        AA_seq.append(' '.join(tmp))
    return AA_seq

# Method to convert 1kmer tokens to integer numbers according to the 1kmer tokenizer and apply pad_sequences

In [ ]:
from keras.utils import pad_sequences
def AA2num(AA_seq,tokenizer,MAX_LEN):
    sequences = tokenizer.texts_to_sequences(AA_seq)
    numseq = pad_sequences(sequences, maxlen=MAX_LEN)
    return numseq, sequences

# Method to convert sequences to integer numbers

In [ ]:
def sentence2num(str_set,tokenizer,MAX_LEN):
    AA_seq=sentence2AA(str_set)
    numseq, sequences =AA2num(AA_seq,tokenizer,MAX_LEN)
    return numseq, AA_seq, sequences

# Get the 1kmer data of the Nanobodies and Antigens based on the 1kmer AA tokenizer

In [ ]:
import pickle
def get_data(nanobodies,antigens):
  with open("sample_data/AminoAcidTokenizer.pickle","rb") as input_:
    tokenizer=pickle.load(input_)
  MAX_LEN=175
  X_Nb, Nb_AAs, Nb_nums=sentence2num(nanobodies,tokenizer,MAX_LEN)
  MAX_LEN=1816
  X_Ag, Ag_AAs, Ag_nums=sentence2num(antigens,tokenizer,MAX_LEN)

  return X_Nb,X_Ag, Nb_AAs, Nb_nums, Ag_AAs, Ag_nums

# Call of the above method and pass to it the sequences of the Nanobodies and Antigens

In [ ]:
X_Nb,X_Ag, Nb_AAs, Nb_nums, Ag_AAs, Ag_nums=get_data(nanobody_sequences_full,antigene_sequences_full)

In [ ]:
nanobody_sequences_full[0]

'MAQVQLLESGGGLVQPGGSLRLSCAASGVTITDEDMTRVRQAPGKGLEWVSSILNTGGSTYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAAVHEKAADMNFWGQGTLVTVSS'

In [ ]:
Nb_AAs[0]

'M A Q V Q L L E S G G G L V Q P G G S L R L S C A A S G V T I T D E D M T R V R Q A P G K G L E W V S S I L N T G G S T Y Y A D S V K G R F T I S R D N S K N T L Y L Q M N S L R A E D T A V Y Y C A A V H E K A A D M N F W G Q G T L V T V S S'

In [ ]:
Nb_nums[0]

[18,
 4,
 13,
 7,
 13,
 1,
 1,
 3,
 2,
 6,
 6,
 6,
 1,
 7,
 13,
 8,
 6,
 6,
 2,
 1,
 9,
 1,
 2,
 19,
 4,
 4,
 2,
 6,
 7,
 10,
 12,
 10,
 11,
 3,
 11,
 18,
 10,
 9,
 7,
 9,
 13,
 4,
 8,
 6,
 5,
 6,
 1,
 3,
 20,
 7,
 2,
 2,
 12,
 1,
 14,
 10,
 6,
 6,
 2,
 10,
 16,
 16,
 4,
 11,
 2,
 7,
 5,
 6,
 9,
 15,
 10,
 12,
 2,
 9,
 11,
 14,
 2,
 5,
 14,
 10,
 1,
 16,
 1,
 13,
 18,
 14,
 2,
 1,
 9,
 4,
 3,
 11,
 10,
 4,
 7,
 16,
 16,
 19,
 4,
 4,
 7,
 17,
 3,
 5,
 4,
 4,
 11,
 18,
 14,
 15,
 20,
 6,
 13,
 6,
 10,
 1,
 7,
 10,
 7,
 2,
 2]

In [ ]:
antigene_sequences_full[0]

'DHNPFISVEWLKGPILEATAGDELVKLPVKLAAYPPPEFQWYKDGKALSGRHSPHALVLKEVTEASTGTYTLALWNSAAGLRRNISLELVVNVPPQIHEKEASSPSIYSRHSRQALTCTAYGVPLPLSIQWHWRPWTPCKMFAQRSLRRRQQQDLMPQCRDWRAVTTQDAVNPIESLDTWTEFVEGKNKTVSKLVIQNANVSAMYKCVVSNKVGQDERLIYFYVTTHHHHHH'

In [ ]:
Ag_AAs[0]

'D H N P F I S V E W L K G P I L E A T A G D E L V K L P V K L A A Y P P P E F Q W Y K D G K A L S G R H S P H A L V L K E V T E A S T G T Y T L A L W N S A A G L R R N I S L E L V V N V P P Q I H E K E A S S P S I Y S R H S R Q A L T C T A Y G V P L P L S I Q W H W R P W T P C K M F A Q R S L R R R Q Q Q D L M P Q C R D W R A V T T Q D A V N P I E S L D T W T E F V E G K N K T V S K L V I Q N A N V S A M Y K C V V S N K V G Q D E R L I Y F Y V T T H H H H H H'

In [ ]:
for index, char in enumerate(tokenizer.word_index):
    print(index , char)

0 l
1 s
2 e
3 a
4 k
5 g
6 v
7 p
8 r
9 t
10 d
11 i
12 q
13 n
14 f
15 y
16 h
17 m
18 c
19 w
20 x
21 u
22 b


In [ ]:
X_Nb[0]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0, 18,  4, 13,  7, 13,  1,  1,  3,  2,  6,  6,  6,  1,  7,
       13,  8,  6,  6,  2,  1,  9,  1,  2, 19,  4,  4,  2,  6,  7, 10, 12,
       10, 11,  3, 11, 18, 10,  9,  7,  9, 13,  4,  8,  6,  5,  6,  1,  3,
       20,  7,  2,  2, 12,  1, 14, 10,  6,  6,  2, 10, 16, 16,  4, 11,  2,
        7,  5,  6,  9, 15, 10, 12,  2,  9, 11, 14,  2,  5, 14, 10,  1, 16,
        1, 13, 18, 14,  2,  1,  9,  4,  3, 11, 10,  4,  7, 16, 16, 19,  4,
        4,  7, 17,  3,  5,  4,  4, 11, 18, 14, 15, 20,  6, 13,  6, 10,  1,
        7, 10,  7,  2,  2], dtype=int32)

# Save the sequences of nanobodies and antigens after pre-processing based on 1kmer

In [ ]:
Data_dir ="sample_data/"
np.savez(Data_dir+'Nb_Ag_pairs_1Kmer.npz',X_Nb=X_Nb,X_Ag=X_Ag,y=np.array(int_hosts))

In [ ]:
Nb_Ag_pairs = np.load("sample_data/Nb_Ag_pairs_1Kmer.npz")

In [ ]:
X_Nb, X_Ag, y = Nb_Ag_pairs['X_Nb'], Nb_Ag_pairs['X_Ag'], Nb_Ag_pairs['y']

In [ ]:
len(X_Nb) , len(X_Nb[0])

(3481, 175)

In [ ]:
X_Nb[0]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0, 18,  4, 13,  7, 13,  1,  1,  3,  2,  6,  6,  6,  1,  7,
       13,  8,  6,  6,  2,  1,  9,  1,  2, 19,  4,  4,  2,  6,  7, 10, 12,
       10, 11,  3, 11, 18, 10,  9,  7,  9, 13,  4,  8,  6,  5,  6,  1,  3,
       20,  7,  2,  2, 12,  1, 14, 10,  6,  6,  2, 10, 16, 16,  4, 11,  2,
        7,  5,  6,  9, 15, 10, 12,  2,  9, 11, 14,  2,  5, 14, 10,  1, 16,
        1, 13, 18, 14,  2,  1,  9,  4,  3, 11, 10,  4,  7, 16, 16, 19,  4,
        4,  7, 17,  3,  5,  4,  4, 11, 18, 14, 15, 20,  6, 13,  6, 10,  1,
        7, 10,  7,  2,  2], dtype=int32)

# Read the protVec embeddings into pandas dataframe

In [ ]:
import pandas as pd
row_protVec=pd.read_csv('sample_data/protVec_100d_3grams.csv', sep="\t")


In [ ]:
row_protVec

words        d1        d2        d3        d4        d5        d6  \
0       AAA -0.174060 -0.095756  0.059515  0.039673 -0.375934 -0.115415   
1       ALA -0.114085 -0.093288  0.155800 -0.037351 -0.121446  0.084037   
2       LLL -0.075594 -0.100834 -0.046616 -0.208980 -0.008596 -0.038612   
3       LAA -0.137546 -0.135425  0.121566 -0.038295 -0.212129  0.040009   
4       AAL -0.156112 -0.133524  0.114426 -0.020264 -0.058513  0.057005   
...     ...       ...       ...       ...       ...       ...       ...   
9043    TXY  0.014640 -0.040339 -0.177313 -0.142597 -0.027828 -0.002875   
9044    XGN  0.012529  0.100273 -0.084018 -0.068436 -0.004238 -0.016091   
9045    XWY -0.078238  0.026070 -0.078415 -0.124451 -0.081429 -0.034911   
9046    XTD  0.090840  0.045846 -0.023550 -0.090981 -0.103220  0.041702   
9047  <unk> -0.036558  0.015085 -0.042163 -0.079190 -0.001883 -0.008346   

            d7        d8        d9  ...       d91       d92       d93  \
0     0.090725  0.173422  0.292520  ...  0.244482  0.015974  0.012903   
1     0.023819  0.093442  0.143256  ...  0.075584 -0.139661  0.034863   
2    -0.049360  0.060720 -0.062662  ...  0.174677 -0.175961 -0.193242   
3     0.078545  0.029837  0.138343  ...  0.133947 -0.156484 -0.048541   
4     0.076881  0.054781  0.129436  ...  0.154597 -0.050440  0.054866   
...        ...       ...       ...  ...       ...       ...       ...   
9043 -0.146911 -0.082518 -0.065310  ...  0.180760  0.137615 -0.179285   
9044 -0.030392  0.065851 -0.028816  ...  0.050221  0.013751  0.008207   
9045 -0.285715 -0.158854 -0.294208  ...  0.027498  0.164893 -0.264212   
9046 -0.113839  0.019155 -0.028805  ...  0.088192  0.182952 -0.223073   
9047 -0.006758 -0.026735 -0.063085  ...  0.008905  0.028574 -0.055239   

           d94       d95       d96       d97       d98       d99      d100  
0     0.137528  0.138140  0.005474  0.070719 -0.164084 -0.179274  0.184899  
1     0.056078  0.028975 -0.012233  0.059669  0.037811 -0.172493  0.074655  
2    -0.072965 -0.075560  0.158286 -0.026378  0.037155 -0.176038  0.319293  
3     0.141848  0.081842  0.070573  0.006927  0.035281 -0.138971  0.105997  
4     0.066185  0.017498  0.001773 -0.083944 -0.003867 -0.106367  0.070706  
...        ...       ...       ...       ...       ...       ...       ...  
9043 -0.050822  0.013805 -0.101486 -0.217593  0.041349 -0.121534 -0.009422  
9044  0.128722  0.051683 -0.084542 -0.041187  0.070509 -0.123749  0.064368  
9045  0.072932  0.135573  0.073504 -0.136748  0.080023 -0.241494  0.131080  
9046 -0.007807 -0.066830 -0.133865 -0.422109  0.116075  0.039210  0.062399  
9047 -0.014421  0.034931 -0.008742 -0.058464 -0.051556 -0.040894  0.093684  

[9048 rows x 101 columns]

In [ ]:
import numpy as np
protVec=np.zeros((8002,100),dtype=np.float32)

In [ ]:
tokenizer = get_tokenizer()

In [ ]:
print(tokenizer.word_index)


{'aaa': 1, 'aac': 2, 'aad': 3, 'aae': 4, 'aaf': 5, 'aag': 6, 'aah': 7, 'aai': 8, 'aak': 9, 'aal': 10, 'aam': 11, 'aan': 12, 'aap': 13, 'aaq': 14, 'aar': 15, 'aas': 16, 'aat': 17, 'aav': 18, 'aaw': 19, 'aay': 20, 'aca': 21, 'acc': 22, 'acd': 23, 'ace': 24, 'acf': 25, 'acg': 26, 'ach': 27, 'aci': 28, 'ack': 29, 'acl': 30, 'acm': 31, 'acn': 32, 'acp': 33, 'acq': 34, 'acr': 35, 'acs': 36, 'act': 37, 'acv': 38, 'acw': 39, 'acy': 40, 'ada': 41, 'adc': 42, 'add': 43, 'ade': 44, 'adf': 45, 'adg': 46, 'adh': 47, 'adi': 48, 'adk': 49, 'adl': 50, 'adm': 51, 'adn': 52, 'adp': 53, 'adq': 54, 'adr': 55, 'ads': 56, 'adt': 57, 'adv': 58, 'adw': 59, 'ady': 60, 'aea': 61, 'aec': 62, 'aed': 63, 'aee': 64, 'aef': 65, 'aeg': 66, 'aeh': 67, 'aei': 68, 'aek': 69, 'ael': 70, 'aem': 71, 'aen': 72, 'aep': 73, 'aeq': 74, 'aer': 75, 'aes': 76, 'aet': 77, 'aev': 78, 'aew': 79, 'aey': 80, 'afa': 81, 'afc': 82, 'afd': 83, 'afe': 84, 'aff': 85, 'afg': 86, 'afh': 87, 'afi': 88, 'afk': 89, 'afl': 90, 'afm': 91, 'afn': 

In [ ]:
count = 0
for index, char in enumerate(tokenizer.word_index):
  print(index, char)
  count += 1
  if count == 5:
    break

0 aaa
1 aac
2 aad
3 aae
4 aaf


In [ ]:
row_protVec.words

0         AAA
1         ALA
2         LLL
3         LAA
4         AAL
        ...  
9043      TXY
9044      XGN
9045      XWY
9046      XTD
9047    <unk>
Name: words, Length: 9048, dtype: object

In [ ]:
for index, row in row_protVec.iterrows():
    print (index,row["words"])

Streaming output truncated to the last 5000 lines.
4048 QDD
4049 RYD
4050 DVM
4051 RTQ
4052 YLH
4053 YRI
4054 NLH
4055 GFY
4056 QDP
4057 KEH
4058 ATH
4059 YAP
4060 HRV
4061 NNR
4062 PDY
4063 RWL
4064 HID
4065 TIY
4066 CAL
4067 AIH
4068 AKM
4069 FTQ
4070 HFL
4071 NQK
4072 YAQ
4073 DHG
4074 HVI
4075 MEI
4076 AYF
4077 WLG
4078 LMN
4079 FNN
4080 FTN
4081 FRT
4082 MTT
4083 DYF
4084 YIN
4085 KPN
4086 SCL
4087 MES
4088 NYS
4089 YTT
4090 YKN
4091 IEH
4092 VHP
4093 GYQ
4094 GLC
4095 DYT
4096 TGM
4097 DYK
4098 VRH
4099 LMQ
4100 YNA
4101 MGK
4102 PIN
4103 GYN
4104 VDH
4105 PML
4106 NQT
4107 YDR
4108 QKN
4109 GRM
4110 NPP
4111 HTV
4112 FRI
4113 DHI
4114 TYV
4115 KYF
4116 SHI
4117 YQG
4118 SME
4119 SMS
4120 SFY
4121 FDQ
4122 DQK
4123 FVQ
4124 PTN
4125 NYG
4126 NKY
4127 VSM
4128 YTD
4129 EIM
4130 RQF
4131 FQS
4132 IYI
4133 IGM
4134 FTF
4135 HRD
4136 MPV
4137 CSL
4138 QLH
4139 DQR
4140 CGA
4141 YNI
4142 VDM
4143 LHF
4144 NTR
4145 HGT
4146 GEH
4147 MDG
4148 MAP
4149 QFI
4150 YPS
4151 MGD
4152 EFY
4153

In [ ]:
count=0
loc =[]
for index, char in enumerate(tokenizer.word_index):
    loc.append(row_protVec.words==char.upper())

In [ ]:
loc

In [ ]:
row_protVec.iloc[-1]

words       <unk>
d1      -0.036558
d2       0.015085
d3      -0.042163
d4       -0.07919
           ...   
d96     -0.008742
d97     -0.058464
d98     -0.051556
d99     -0.040894
d100     0.093684
Name: 9047, Length: 101, dtype: object

In [ ]:
np.array(row_protVec.iloc[-1])[1:101].reshape(100,)

array([-0.0365576142793988, 0.0150848404067197, -0.0421630539345713,
       -0.0791904971264365, -0.0018829488284704, -0.0083460720601238,
       -0.0067578688107869, -0.026734716954023, -0.0630853951149427,
       0.0684358414014147, 0.0052617267904509, -0.0335999732537577,
       -0.0045534215296197, 0.0018043001768346, -0.0237892017020336,
       0.0107441864500442, 0.037585730327144, -0.0336586401414678,
       -0.0249018978779841, -0.0231389745800177, -0.0036198517904509,
       -0.0317930816755084, -0.0616961456675507, 0.0458140505083996,
       0.0044602764146772, -0.0255747749778956, -0.0488459209770116,
       -0.0010153541114058, 0.0292818015030946, 0.0003720965959328,
       -0.0142972078912467, -0.0429948863837311, 0.0293992107648098,
       -0.0181502973032715, 0.0669065242042438, 0.0219559259504864,
       -0.0448854582228119, 0.0181411231211318, -0.0086847864721485,
       -0.0189086151635721, 0.002492315760389, 0.0042003215075155,
       0.0342378280282936, -0.026829626

In [ ]:
count=0
for index, char in enumerate(tokenizer.word_index):
    count+=1;
    print (count)
    protVec[index+1,:]= np.array(row_protVec.loc[row_protVec.words==char.upper()])[:,1:101].reshape(100,)
    if count ==8000:
        break
protVec[8001,:]= np.array(row_protVec.iloc[-1])[1:101].reshape(100,)



Streaming output truncated to the last 5000 lines.
3001
3002
3003
3004
3005
3006
3007
3008
3009
3010
3011
3012
3013
3014
3015
3016
3017
3018
3019
3020
3021
3022
3023
3024
3025
3026
3027
3028
3029
3030
3031
3032
3033
3034
3035
3036
3037
3038
3039
3040
3041
3042
3043
3044
3045
3046
3047
3048
3049
3050
3051
3052
3053
3054
3055
3056
3057
3058
3059
3060
3061
3062
3063
3064
3065
3066
3067
3068
3069
3070
3071
3072
3073
3074
3075
3076
3077
3078
3079
3080
3081
3082
3083
3084
3085
3086
3087
3088
3089
3090
3091
3092
3093
3094
3095
3096
3097
3098
3099
3100
3101
3102
3103
3104
3105
3106
3107
3108
3109
3110
3111
3112
3113
3114
3115
3116
3117
3118
3119
3120
3121
3122
3123
3124
3125
3126
3127
3128
3129
3130
3131
3132
3133
3134
3135
3136
3137
3138
3139
3140
3141
3142
3143
3144
3145
3146
3147
3148
3149
3150
3151
3152
3153
3154
3155
3156
3157
3158
3159
3160
3161
3162
3163
3164
3165
3166
3167
3168
3169
3170
3171
3172
3173
3174
3175
3176
3177
3178
3179
3180
3181
3182
3183
3184
3185
3186
3187
3188
3189
3190

In [ ]:
protVec

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.17406   , -0.095756  ,  0.059515  , ..., -0.164084  ,
        -0.179274  ,  0.184899  ],
       [-0.046847  ,  0.061735  , -0.009397  , ...,  0.024218  ,
        -0.299657  ,  0.267578  ],
       ...,
       [-0.042674  ,  0.017984  ,  0.020126  , ..., -0.275342  ,
         0.077792  , -0.016541  ],
       [-0.129372  ,  0.025773  , -0.111673  , ..., -0.302059  ,
        -0.042755  ,  0.134562  ],
       [-0.03655761,  0.01508484, -0.04216306, ..., -0.05155624,
        -0.04089434,  0.09368438]], dtype=float32)

In [ ]:
len(protVec), len(protVec[0])

(8002, 100)

In [ ]:
protVec[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [ ]:
protVec[8001]

array([-0.03655761,  0.01508484, -0.04216306, -0.0791905 , -0.00188295,
       -0.00834607, -0.00675787, -0.02673472, -0.06308539,  0.06843584,
        0.00526173, -0.03359997, -0.00455342,  0.0018043 , -0.0237892 ,
        0.01074419,  0.03758573, -0.03365864, -0.0249019 , -0.02313897,
       -0.00361985, -0.03179308, -0.06169615,  0.04581405,  0.00446028,
       -0.02557478, -0.04884592, -0.00101535,  0.0292818 ,  0.0003721 ,
       -0.01429721, -0.04299489,  0.02939921, -0.0181503 ,  0.06690653,
        0.02195593, -0.04488546,  0.01814112, -0.00868479, -0.01890861,
        0.00249232,  0.00420032,  0.03423783, -0.02682963, -0.00254612,
        0.0048285 , -0.05335173, -0.00447328, -0.01865933,  0.03423391,
       -0.02694846, -0.01403855,  0.00325714, -0.05769052,  0.03716011,
       -0.05928952,  0.00092933, -0.01298835, -0.0153933 , -0.02405057,
       -0.00515015,  0.07767964,  0.00226443, -0.03003707,  0.074504  ,
       -0.0188211 , -0.03460462,  0.02098261,  0.05312847, -0.02

In [ ]:
protVec[1]

array([-1.74060e-01, -9.57560e-02,  5.95150e-02,  3.96730e-02,
       -3.75934e-01, -1.15415e-01,  9.07250e-02,  1.73422e-01,
        2.92520e-01,  1.90375e-01,  9.40910e-02, -1.97482e-01,
       -1.35202e-01,  7.55210e-02,  1.10771e-01,  4.79090e-02,
       -3.91934e-01,  7.35480e-02,  1.03868e-01, -4.59240e-02,
       -9.53400e-03,  5.56590e-02, -3.08000e-04,  2.15941e-01,
        8.44760e-02,  6.15730e-02,  1.28139e-01,  1.84247e-01,
       -1.00091e-01, -1.26661e-01, -5.72800e-03, -3.82720e-02,
        1.80597e-01, -1.55310e-01,  5.62320e-02, -5.92500e-03,
       -8.53810e-02, -5.69210e-02, -4.55200e-02,  2.65116e-01,
        9.02210e-02, -2.09879e-01,  2.05381e-01,  2.36790e-02,
       -9.29390e-02,  7.27670e-02, -1.05107e-01,  1.11120e-02,
       -1.60518e-01,  4.26270e-02,  1.51230e-01, -1.62708e-01,
       -8.34790e-02, -1.46657e-01,  9.13320e-02,  1.09579e-01,
       -1.01678e-01,  9.11980e-02,  5.51200e-03,  4.73180e-02,
        7.81080e-02,  2.03824e-01, -1.00126e-01,  2.947

In [ ]:
protVec[8000]

array([-0.129372,  0.025773, -0.111673, -0.118027,  0.030318, -0.156755,
        0.126657,  0.007195, -0.139285,  0.068238, -0.025435, -0.02135 ,
        0.027871, -0.019361,  0.024047, -0.055712,  0.090152, -0.013237,
       -0.155394, -0.163564,  0.216671,  0.155781, -0.041615, -0.047935,
       -0.073997, -0.019505, -0.073821, -0.042981,  0.065991, -0.03414 ,
       -0.074147, -0.160329,  0.256311, -0.088629,  0.084412,  0.081061,
       -0.110804,  0.202938, -0.084171, -0.080367,  0.070977,  0.010862,
        0.009541,  0.084735,  0.012971, -0.07125 , -0.057154, -0.015896,
        0.05206 ,  0.179335,  0.104214, -0.144926, -0.00513 , -0.222448,
       -0.127892, -0.021637,  0.03742 , -0.129511, -0.068888, -0.087548,
       -0.167942, -0.014151,  0.071191, -0.159533,  0.020309, -0.074896,
       -0.175363,  0.104328, -0.036038, -0.072138,  0.030034, -0.005432,
       -0.164844, -0.229754,  0.090145,  0.066878,  0.011238, -0.057198,
       -0.020514, -0.074585, -0.117986,  0.044145, 

In [ ]:
path = ('sample_data/protVec_embedding.npy')
np.save(path, protVec)

# create a dic for the onehot embedding

In [ ]:
oneHotMap = {'AA':['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y'],
             'd1': [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             'd2': [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             'd3': [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             'd4': [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             'd5': [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             'd6': [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             'd7': [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             'd8': [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             'd9': [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             'd10': [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             'd11': [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
             'd12': [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
             'd13': [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
             'd14': [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
             'd15': [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
             'd16': [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
             'd17': [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
             'd18': [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
             'd19': [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
             'd20': [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]
                 }

# convert the one-hot dic into pandas dataframe

In [ ]:
import pandas as pd
row_oneHot = pd.DataFrame.from_dict(oneHotMap)

In [ ]:
row_oneHot

AA   d1   d2   d3   d4   d5   d6   d7   d8   d9  ...  d11  d12  d13  d14  \
0   A  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1   C  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2   D  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3   E  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4   F  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
5   G  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
6   H  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
7   I  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0  0.0   
8   K  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0  0.0   
9   L  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
10  M  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0  0.0   
11  N  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0  0.0   
12  P  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0   
13  Q  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0   
14  R  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
15  S  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
16  T  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
17  V  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
18  W  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
19  Y  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    d15  d16  d17  d18  d19  d20  
0   0.0  0.0  0.0  0.0  0.0  0.0  
1   0.0  0.0  0.0  0.0  0.0  0.0  
2   0.0  0.0  0.0  0.0  0.0  0.0  
3   0.0  0.0  0.0  0.0  0.0  0.0  
4   0.0  0.0  0.0  0.0  0.0  0.0  
5   0.0  0.0  0.0  0.0  0.0  0.0  
6   0.0  0.0  0.0  0.0  0.0  0.0  
7   0.0  0.0  0.0  0.0  0.0  0.0  
8   0.0  0.0  0.0  0.0  0.0  0.0  
9   0.0  0.0  0.0  0.0  0.0  0.0  
10  0.0  0.0  0.0  0.0  0.0  0.0  
11  0.0  0.0  0.0  0.0  0.0  0.0  
12  0.0  0.0  0.0  0.0  0.0  0.0  
13  0.0  0.0  0.0  0.0  0.0  0.0  
14  1.0  0.0  0.0  0.0  0.0  0.0  
15  0.0  1.0  0.0  0.0  0.0  0.0  
16  0.0  0.0  1.0  0.0  0.0  0.0  
17  0.0  0.0  0.0  1.0  0.0  0.0  
18  0.0  0.0  0.0  0.0  1.0  0.0  
19  0.0  0.0  0.0  0.0  0.0  1.0  

[20 rows x 21 columns]

# Create numpy array for the onehot embeddings

In [ ]:
oneHot=np.zeros((21,20),dtype=np.float32)

In [ ]:
pip install Keras-Preprocessing

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 1.2 MB/s eta 0:00:00


In [ ]:
import pickle
with open("sample_data/AminoAcidTokenizer.pickle","rb") as input_:
    tokenizer=pickle.load(input_)


# Store the onehot embeddings into the numpy array

In [ ]:
count=0
for index, char in enumerate(tokenizer.word_index):
    #print(index , char)
    count+=1;
    oneHot[index+1,:]= np.array(row_oneHot.loc[row_oneHot.AA==char.upper()])[:,1:21].reshape(20,)
    #print(oneHot[index+1,:])
    if count ==20:
        break

In [ ]:
oneHot

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

# Save the one-hot embeddings as npy file

In [ ]:

path = ('sample_data/oneHot_embedding.npy')
np.save(path, oneHot)